#Grant Wilkins
#CPSC 111 Section 001 Fall 19
#Make file to compile, run, and clean lab10.
lab10: lab12.c arrayProcessing.c
	gcc -o lab12 lab12.c arrayProcessing.c

run: lab12
	./lab12 leanProteins.txt

clean:
	rm lab12
